### ISSUE TITLE
Add file navigator instead of textfield on export

### ISSUE THREAD

**Issue by Xaviju** [kaleidos/inkscape-navigator#2]
I have towrite the export field every time I export something. It is a pain. It would be nice to find out how to make a file path selector by UI.

**Comment by Xaviju** [comment]
Seems that inkscape extensions do not allow file selector from UI. :disappointed:

**Comment by superalex** [comment]
Exactly -> http://wiki.inkscape.org/wiki/index.php/INX_Parameters

It only support basic types

**Comment by Xaviju** [comment]
There is already a bug on inkscape and it is confirmed.
It would be nice to add an "also affects me" so it increases priority :) 
https://bugs.launchpad.net/inkscape/+bug/1070193
